---
title: "The rating system"
output: html_fragment
---

The rating system is an Elo rating system.  
This is a method in which a player's rating is calculated based on his previous
experience.  

#### **New players**

New players are given a rating of 750.  
Consequently, new players are not at the bottom of the ranking although they are
not ranked too high either!
    
#### **Update the rating**

 A player's rank is updated taking into account the rank of the opponent.  For
example, a highly ranked player plays against a lowly ranked player. 

 * If the highly ranked player wins: his rating is increased by a small amount
 * If the lowly ranked player wins: his rating is increased by a huge amount
	
The updating of the rating consists of the following steps:

##### **Step 1**  
 
 Assume a player has rating $R$ and the opponent has rating $R_i$.	
 Calculate the expected score of the player as:
		
 $$ E_{R} =  \frac{1}{1+10^{-(R-R_i)/400}} $$
	 	
##### **Step 2**  
 
The rank of the player is updated based on parameters *K* and *S*.  

The parameter *K* is factor that determines how much the ratings will change:

\[
K = \left\{ 
\begin{array}{l}     
        32 \quad \text{if $R < 2100$}\\     
        24 \quad \text{if $2100 < R <2400$}\\     
        16 \quad \text{if $R > 2400$}\\  
\end{array} 
\right.
\]

The parameter $S$ represents the score, taking into account the result of the
petanque game:

\[
 S = \left\{  
 \begin{array}{l}     
    0 \quad \text{for a loss}\\     
    1 \quad \text{for a win}+\left\{  
\begin{array}{l}          0.0 \quad \text{if petanque score = 1}\\         
                          0.3 \quad \text{if petanque score = 2}\\
                          0.6 \quad \text{if petanque score = 3}\\ 
                          \end{array}
\right. 
\end{array} 
\right. 
\]

The rating of the player is updated by: 

 $$R^{'} = R + K \cdot (S - E_{R})$$
 
 
Game on! 

